language: php

services:
- mysql

php:
- 7.1

before_script:
- cp .env.testing .env
- composer install --no-interaction
- php artisan key:generate --force
- php artisan jwt:secret --force

script:
- php artisan unitTest --env=testing