<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    static $databaseReady = false;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $sqliteDb = base_path().DIRECTORY_SEPARATOR.env('DB_DATABASE');
        // create the database file if not existes
        if(!file_exists($sqliteDb))
        {
            touch($sqliteDb);
        }
        //run migrations if the database is not ready
        if(!self::$databaseReady)
        {
            $this->artisan('migrate:refresh');
            $this->artisan('db:seed');
            self::$databaseReady = true;
        }
    }
}
